### ISSUE TITLE
Bug in the Unit Test

### ISSUE THREAD

**Issue by GJNilsen** [andrewcbancroft/Zootastic#2]
Getting the following on line 18 in the unit test:

Zootastic-NSFetchedResultsController_DisplayInTableView/ZootasticTests/ZootasticTests.swift:18:26: 'DataHelper' cannot be constructed because it has no accessible initializers

**Comment by andrewcbancroft** [comment]
Thank you for identifying that!

**Comment by andrewcbancroft** [comment]
I just now got to checking this out, but I can't reproduce any errors - the project builds and runs fine.

Interestingly, I don't have any unit tests included with this project.  Are you trying to write one of your own and are getting this error?  If so, the error is indicating that there are no `public` init functions on the `DataHelper` (which is true).  You'd simply need to go over to DataHelper.swift, and make it the init function `public`.

**Comment by andrewcbancroft** [comment]
I've just now gotten a chance to look at this - I'm not getting the same error as you.  All branches build and run fine, and all tests pass.  Can you make sure you've got the latest code from this repository?
